# Generated by Django 5.2.10 on 2026-01-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_historicalcourse_remove_historicaltask_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Обложка курса'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Обложка курса'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
