# Generated by Django 5.2.10 on 2026-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course_image_historicalcourse_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID сущности'),
        ),
    ]
